language: php

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs
 
script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_success:
    - vendor/bin/coveralls --no-interaction
